<a href="https://colab.research.google.com/github/phzfi/ai-course/blob/main/nn/flip_flop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

def generate_bistable_data(seq_length=10, num_sequences=10000):
    X = np.random.randint(0, 3, (num_sequences, seq_length, 1))  # 0: reset, 1: set, 2: hold
    Y = np.zeros((num_sequences, seq_length, 1))
    for i in range(num_sequences):
        state = 0
        for j in range(seq_length):
            if X[i, j] == 0:  # reset
                state = 0
            elif X[i, j] == 1:  # set
                state = 1
            Y[i, j] = state
    return X, Y

# Generate data
X, Y = generate_bistable_data()
print("Input sequences:\n", X[:2].reshape(2,10))
print("Output sequences:\n", Y[:2].reshape(2,10))


Input sequences:
 [[0 2 0 0 2 0 2 1 2 1]
 [1 0 0 2 2 1 2 2 2 2]]
Output sequences:
 [[0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, TimeDistributed

model = Sequential([
    LSTM(10, input_shape=(None, 1), return_sequences=True),
    TimeDistributed(Dense(1, activation='sigmoid'))
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, None, 8)           320       
                                                                 
 time_distributed (TimeDist  (None, None, 1)           9         
 ributed)                                                        
                                                                 
Total params: 329 (1.29 KB)
Trainable params: 329 (1.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
model.fit(X, Y, epochs=10, batch_size=32, verbose=1, validation_split=0.1)

Epoch 1/10
282/282 [==============================] - 7s 13ms/step - loss: 0.6578 - accuracy: 0.6258 - val_loss: 0.6031 - val_accuracy: 0.6646
Epoch 2/10
282/282 [==============================] - 2s 8ms/step - loss: 0.5240 - accuracy: 0.7073 - val_loss: 0.4595 - val_accuracy: 0.7939
Epoch 3/10
282/282 [==============================] - 2s 6ms/step - loss: 0.4077 - accuracy: 0.8094 - val_loss: 0.3706 - val_accuracy: 0.8175
Epoch 4/10
282/282 [==============================] - 2s 5ms/step - loss: 0.3261 - accuracy: 0.8537 - val_loss: 0.2897 - val_accuracy: 0.9080
Epoch 5/10
282/282 [==============================] - 2s 6ms/step - loss: 0.2419 - accuracy: 0.9589 - val_loss: 0.2035 - val_accuracy: 0.9799
Epoch 6/10
282/282 [==============================] - 2s 6ms/step - loss: 0.1647 - accuracy: 0.9853 - val_loss: 0.1345 - val_accuracy: 0.9870
Epoch 7/10
282/282 [==============================] - 2s 7ms/step - loss: 0.1086 - accuracy: 0.9942 - val_loss: 0.0888 - val_accuracy: 0.9949
Epoch

In [12]:
# Evaluate the model
loss, accuracy = model.evaluate(X, Y, verbose=0)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Test the model with some sequences
test_sequences, test_labels = generate_bistable_data(num_sequences=5)
predictions = model.predict(test_sequences)

print("Test sequences:")
print(test_sequences.reshape(5,10))
print("\nPredictions (rounded):")
print(np.round(predictions.reshape(5,10)).astype(int))
print("\nActual:")
print(test_labels.reshape(5,10).astype(int))


Accuracy: 100.00%
1/1 [==============================] - 0s 22ms/step
Test sequences:
[[1 1 2 2 2 2 2 1 1 1]
 [0 0 0 2 1 1 0 2 2 2]
 [1 2 0 2 0 2 0 2 2 0]
 [1 2 1 2 0 2 2 2 1 2]
 [1 0 1 2 0 2 2 1 0 0]]

Predictions (rounded):
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1]
 [1 0 1 1 0 0 0 1 0 0]]

Actual:
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1]
 [1 0 1 1 0 0 0 1 0 0]]
